### ISSUE TITLE
Docs do not build with Sphinx 4.0.2

### ISSUE THREAD

**Issue by johndavidmiller** [jaidevd/pyhht#65]
I'm trying to build the docs and it throws this error.  I think it must be a version thing, i.e., the `add_javascript` method probably went away with Sphinx v4.x

```sh
pyhht/docs $ make singlehtml
sphinx-build -b singlehtml -d build/doctrees   source build/singlehtml
Running Sphinx v4.0.2
making output directory... done

Exception occurred:
  File "/Users/jdm/Dropbox/Tools/Software/Python/pyhht/docs/source/conf.py", line 282, in setup
    app.add_javascript("https://docs.python.org/2/_static/copybutton.js")
AttributeError: 'Sphinx' object has no attribute 'add_javascript'
The full traceback has been saved in /var/folders/cs/lqjsdh5s69dd7csnhrxwmbgm0000gn/T/sphinx-err-gnmyqxeg.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [singlehtml] Error 2
```

And the log file shows this:

```sh
pyhht/docs $ more /var/folders/cs/lqjsdh5s69dd7csnhrxwmbgm0000gn/T/sphinx-err-gnmyqxeg.log
# Sphinx version: 4.0.2
# Python version: 3.8.8 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 2.11.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/Applications/anaconda3/lib/python3.8/site-packages/sphinx/application.py", line 257, in __init__
    self.config.setup(self)
  File "/Users/jdm/Dropbox/Tools/Software/Python/pyhht/docs/source/conf.py", line 282, in setup
    app.add_javascript("https://docs.python.org/2/_static/copybutton.js")
AttributeError: 'Sphinx' object has no attribute 'add_javascript'
```

**Comment by jaidevd** [comment]
Thanks for pointing this out, @johndavidmiller 

This is a result of not updating sphinx builds for a while. I'll see what I can do.

**Comment by johndavidmiller** [comment]
I just down-rev’d sphinx and it went w/o errors.

So no rush from my need

-- jdm

**Comment by jaidevd** [comment]
@johndavidmiller 

This should now work with Sphinx 4.0.2. You only have to update the dependencies. Specifically, do

```bash
pip install --upgrade tftb
```

And then the standard sphinx build should work from the latest `dev` branch.

Thanks, do let me know if there's a problem.

**Comment by johndavidmiller** [comment]
Thanks!


-- jdm
